version: '3'

services:

  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    depends_on:
      - "db"
    environment:
      - database_client=mysql
      - database_connection_host=db
      - database__connection__user=root
      - database_connection_password=password
      - database_connection_database=ghost

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password